@url = http://localhost:3000

###

GET {{url}}

###
GET {{url}}/set

###
GET {{url}}/get

###
GET {{url}}/clear/testplaincookie1

###
POST {{url}}/api/signup
content-type: application/json

{
    "email": "sample",
    "password": "sample"
}